In [3]:
import pandas as pd
import numpy as np

data = {
    'Hoc sinh': ['HS1', 'HS2', 'HS3', 'HS4', 'HS5'],
    'Toan': [80, 70, 90, 60, 75],
    'Ly': [85, 75, 95, 65, 70],
    'Hoa': [90, 80, 85, 70, 75]
}
df = pd.DataFrame(data)
df.head()

  Hoc sinh  Toan  Ly  Hoa
0      HS1    80  85   90
1      HS2    70  75   80
2      HS3    90  95   85
3      HS4    60  65   70
4      HS5    75  70   75

In [5]:
mean_scores = df [['Toan', 'Ly', 'Hoa']].mean()
std_scores = df [['Toan', 'Ly', 'Hoa']].std(ddof=0)

In [7]:
standardized_df = df.copy()
standardized_df[['Toan', 'Ly', 'Hoa']] = (df[['Toan', 'Ly', 'Hoa']] - mean_scores) / std_scores

standardized_df.head()

  Hoc sinh  Toan        Ly       Hoa
0      HS1   0.5  0.649934  1.414214
1      HS2  -0.5 -0.278543  0.000000
2      HS3   1.5  1.578410  0.707107
3      HS4  -1.5 -1.207020 -1.414214
4      HS5   0.0 -0.742781 -0.707107

In [8]:
cov_matrix = standardized_df[['Toan', 'Ly', 'Hoa']].cov(ddof=0)
print("Covariance matrix:\n", cov_matrix)

Covariance matrix:
           Toan        Ly       Hoa
Toan  1.000000  0.928477  0.777817
Ly    0.928477  1.000000  0.853492
Hoa   0.777817  0.853492  1.000000

In [9]:
eig_val, eig_vec = np.linalg.eig(cov_matrix)
print("Eigen values:\n", eig_val)
print("Eigen vectors:\n", eig_vec)

Eigen values:
 [2.70800231 0.0590315  0.23296619]
Eigen vectors:
 [[-0.57779799 -0.58368886 -0.57048821]
 [-0.59386823  0.78014286 -0.19671717]
 [-0.55988392 -0.22513204  0.79739924]]

In [16]:
selected_eig_vec = eig_vec[:, [0, 2]]
reduced_data = standardized_df[['Toan', 'Ly', 'Hoa']].dot(selected_eig_vec)
reduced_data.columns = ['PC1', 'PC3']
print("Reduced data:\n", reduced_data)

Reduced data:
         PC1       PC3
0 -1.466669  0.714596
1  0.454317  0.340038
2 -2.199962 -0.602386
3  2.375303 -0.034519
4  0.837012 -0.417729

In [17]:
new_data = reduced_data.values

In [ ]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2, random_state=0).fit(new_data)
print("Cluster labels :", kmeans.labels_) # Result : [0 1 0 1 1]
print("Cluster centers :", kmeans.cluster_centers_)

 Cluster labels : [0 1 0 1 1]
 Cluster centers : [[-1.83331594  0.05610464]
 [ 1.22221063 -0.03740309]]

In [ ]:
class KMeans:
    def __init__(self, k_cluster=None, max_it=100, tol=1e4, random_state=42):
        self.k_cluster = k_cluster
        self.max_it = max_it
        self.tol = tol
        self.random_state = random_state
        self.centroid = []

    def fit(self, X):
        if self.random_state is not None:
            np.random_seed(self.random_state)

        num_feature = X.shape[0]
        centroids = np.random.rand(self.k, num_feature)[:self.k]

        for